services:
type: web 
name: wealth-wise
runtime: python
plan: free
build_command: pip install -r requirements.txt && python -m data.seed
startcommand: gunicorn app:app -- bind 0.0.0.0:SPORT
envVars:
  - key: PYTHON_VERSION
    value: 3.11.11
  - key: SECRET_KEY
    generatevalue: true
  - key: CURRENCY_SYMBOL
    value: R
  - key: DATABASE_URL
    value: sqlite:///data/finance.db 